### ISSUE TITLE
How do I search more than one word separated by whitespace?

### ISSUE THREAD

**Issue by edukmattos** [remoteportal/substring_highlight#2]
I have the following records:
My horse is white.
My house is white.
My horn is broked.

When I search with this setence: "ho whit"

The result of the filter should be :
My (ho)rse is (whit)e. >> success
My (ho)use is (whit)e.>> success
My (ho)rn is broked >> error

**Comment by remoteportal** [comment]
As it stands, searching for "ho whit" would only match that exactly character sequence which I think is a very important use case (to allow searching for spaces in the search term).

In contrast, I think you're asking for the ability to search for an array: ["ho", "whit"].    Let me think about that for a day or so.

**Comment by fryette** [comment]
@remoteportal any news on it?

**Comment by fenchai23** [comment]
yeah multi strings support is what I need in my life :(

**Comment by gerald-tetteh** [comment]
I have created a pull request for multi string support.

**Comment by remoteportal** [comment]
Sorry for the delay... I know it was a YEAR.  You've probably moved on.

If you haven't, with version 1.0.26 you can now pass terms list of strings.

**Comment by fenchai23** [comment]
about damn time 😂 I am using another package that converts whatever you wrap into whatever style you want to style. kinda like html but you can customize it.

This will be pretty good for simpler tasks and will definitely revisit.
