### ISSUE TITLE
Add support for overflow property?

### ISSUE THREAD

**Issue by ozasadnyy** [remoteportal/substring_highlight#4]
Thanks for the library!

I would like to have one line text and set overflow: TextOverflow.ellipsis for the text.

**Comment by marcjoha** [comment]
Implemented this in a fork and sent a PR: https://github.com/remoteportal/substring_highlight/pull/5

**Comment by remoteportal** [comment]
Fixed in Version 1.0.25.

SORRY IT TOOK SO LONG!
